version: '3'
services:
  logic:
    build: ./cpp
    image: cpprun
    ports: 
     - "1024:1024"
    volumes:
     - ./temp/:/temp
    command: /temp/
    tty: true    
  web:
    build: ./java
    image: javarun
    ports: 
     - "8089:8080"
    volumes:
     - ./temp/:/temp
     - ./kaldi/:/kaldi
    environment: 
     - speakers.directory=/temp/
